# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "*/30 * * * *"  
    # scheduled at 1 MIN every day 
  workflow_dispatch:
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull upstream changes
      id: sync
      uses: tgymnich/fork-sync@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_repository: freefq/free
        upstream_branch: master
        target_branch: master

    - name: Timestamp
      run: date
